# Curriculum Vitae

About me:

Studied life sciences with major in molecular biology, transitioning into the field of data science. 
Having experience in R programming and bash, I am eager to use my analytical skills on complex data sets combined with programming to gain data-driven insights into biological processes. Or to build on projects that help facilitate and advance the process of analytics and research.

Personalia<br>
Name &nbsp; Alex Groot <br>
Location &nbsp; Haarlemmermeer, The Netherlands <br>
Email &nbsp; Alex_groot@icloud.com <br>

Education <br>
Biologie en Medisch Laboratoriumonderzoek HBO Bachelor <br>
Specialisatie Biomolecular Research <br>

Data science skills <br>
R (programming language)<br>
R Quarto <br>
R Shiny <br>
Git<br>
Data visualisation<br>
Bash<br>
Microsoft Excel<br>

Workexperience<br>
Project Nanopore: <br>
Processing MinION Nanopore RNA-seq data
IGV browser

Project genes and proteins:<br>
Transfecting eukaryote cells with recombinant plasmids<br>
SDS-PAGE<br>
Western-blot<br>

Project sphingolipids:<br>
Literature research<br>
Working with multiple cell ines (SKNAS, HEK293T, HEPG2).<br>
Setting up and performing assays (MTT, Amplex Red)<br>
Thin Layer Chromatography (TLC)<br>