project:
  type: website

website:
  title: "Data science portfolio"
  sidebar:
    contents: /*
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: united
    css: styles.css
    toc: true