project:
  type: website

website:
  title: "AlexPGroot"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
  sidebar:
      contents:
        - text: Home
          href: index.qmd
        - projects.qmd
        - 001_CV.qmd
        - 002_Looking_ahead.qmd
        - 003_Guerrilla_analytics_framework.qmd
        - text: C elegans analysis
          href: 004_C_elegans.qmd
        - 005_open_peer_review.qmd
        - text: R Package
          href: https://github.com/AlexPGroot/mytoolkitr
        - text: RNAseq introduction
          href: 008_Zotero.qmd
        - 009_Parameterized_report.qmd
        - 010_ML_Getting_started.qmd
        - text: Interactive R Shiny App Report
          href: https://alexpgroot.shinyapps.io/dsfb2_deploy/
  site-url: https://alexpgroot.github.io/
  page-footer: 
    center: | 
      &copy; 2024, Alex Groot
    right: 
      - icon: github
        href: https://github.com/AlexPGroot/AlexPGroot.github.io
format:
  html:
    code-tools: 
      source: true
      toggle: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    code-links:
      - text: Github
        icon: github
        href: https://github.com/AlexPGroot/AlexPGroot.github.io
    theme: 
      light: united
    css: styles.css
    toc: true
    
include-in-header:
  - text: |
      <style>
      /* tabset format and border removal */
      .panel-tabset > .nav-tabs,
      .panel-tabset > .tab-content {
        border: none;
      }
      </style>